iocage start: fix wrong hexmask for newer freebsd versions.
iocage/iocage pull request #1295
Opened 2023-10-02 02:45 UTC by sueszli

the `iocage start` command has bit math that's unnecessary on newer freebsd versions.

to keep backwards compatibility a version check was introduced that runs the old code for freebsd <12.X.

2023-11-23 16:09 UTC, dgeo requested changes
should be <11, as FreeBSD 11 can use -f inet:cidr

2023-11-23 16:09 UTC, dgeo commented on iocage_lib/ioc_start.py
> +                if freebsd_version_major < 12:
should'n it be < 11 ?

2023-11-23 17:59 UTC, sueszli commented
correct - thank you for updating

2023-11-26 00:43 UTC, sueszli commented
any updates?

2023-11-26 07:31 UTC, dgeo approved these changes
Thank you

2023-11-26 17:02 UTC, sueszli commented
thank you!

2024-04-04 18:36 UTC, closed without merging