Review advanced-use.rst
iocage/iocage pull request #242
Opened 2017-07-03 16:12 UTC by Mrt134

(Ignored text accuracy for this commit)
Updated advanced-use.rst with:
- Grammar fixes
- Syntax fixes (ReST/Sphinx)
- Emphasis on important words.
- Rewrite/reorganize sentences for clarity.
- PEP8 fixes.
- White spacing fixes.

Make sure to follow and check these boxes before submitting a PR! Thank you.

- [ ] Explain the feature
- [ ] Read [CONTRIBUTING.md](https://github.com/iocage/iocage/blob/master/CONTRIBUTING.md)

2017-07-05 20:57 UTC, skarekrow requested changes

2017-07-05 20:57 UTC, skarekrow commented on doc/source/advanced-use.rst
> +:samp:`# iocage clone www01 tag=www02`
TAGS are being dropped, use `--name` instead

2017-07-05 20:57 UTC, skarekrow commented on doc/source/advanced-use.rst
> +:samp:`# iocage clone www01@snapshotname tag=www03`
Same as above

2017-07-05 20:57 UTC, skarekrow commented on doc/source/advanced-use.rst
> +:samp:`# iocage promote UUID | TAG`
s/TAG/NAME/, but make it clear promote isn't in yet.

2017-07-05 20:57 UTC, skarekrow commented on doc/source/advanced-use.rst
> +:samp:`# iocage destroy UUID | TAG`
s/TAG/NAME/

2017-07-05 20:57 UTC, skarekrow commented on doc/source/advanced-use.rst
> +:samp:`# iocage update UUID | TAG`
s/TAG/NAME/

2017-07-05 20:57 UTC, skarekrow commented on doc/source/advanced-use.rst
> +:samp:`# iocage snapremove UUID|TAG@snapshotname`
s/TAG/NAME/ and the user is now responsible for the snapshots, that may change in the future if I port that functionality back, but currently we don't do it automatically.

2017-07-05 20:57 UTC, skarekrow commented on doc/source/advanced-use.rst
> +:samp:`# iocage rollback UUID|TAG@snapshotname`
Drop this and the previous line.

2017-07-05 20:57 UTC, skarekrow commented on doc/source/advanced-use.rst
> +:samp:`# iocage clone UUID|TAG tag=testupdate`
s/TAG/NAME/ and use `--name` not `tag`.

2017-07-05 20:57 UTC, skarekrow commented on doc/source/advanced-use.rst
> +version (visible with uname -r).
No longer true, the user must supply `--release`

2017-07-05 20:57 UTC, skarekrow commented on doc/source/advanced-use.rst
> +:samp:`# iocage upgrade UUID | TAG`
`iocage upgrade -r 11.1-RELEASE UUID | NAME`

2017-07-05 20:57 UTC, skarekrow commented on doc/source/advanced-use.rst
> +:samp:`# iocage upgrade UUID|TAG release=10.1-RELEASE`
Drop this and previous 2 lines

2017-07-05 20:57 UTC, skarekrow commented on doc/source/advanced-use.rst
>  ++++++++++++++++
The entire basejail section needs a disclaimer that this upgrade mechanism for them is not written yet. So possibly remove it entirely or make it known that this is only for the old legacy implementation for now.

2017-07-05 20:57 UTC, skarekrow commented on doc/source/advanced-use.rst
> +:samp:`# iocage set boot=on UUID|TAG`
s/TAG/NAME/

2017-07-05 20:57 UTC, skarekrow commented on doc/source/advanced-use.rst
> +:samp:`# iocage set priority=20 UUID|TAG`
s/TAG/NAME/

2017-07-05 20:57 UTC, skarekrow commented on doc/source/advanced-use.rst
> +:samp:`# iocage snaplist UUID|TAG`
s/TAG/NAME/

2017-07-05 20:57 UTC, skarekrow commented on doc/source/advanced-use.rst
> +:samp:`# iocage snapshot UUID|TAG`
`iocage snapshot -n NAME UUID|NAME` we require they supply a name now.

2017-07-05 20:57 UTC, skarekrow commented on doc/source/advanced-use.rst
> +:samp:`# iocage snapshot UUID|TAG@mysnapshotname`
Remove this and previous 2 lines.

2017-07-05 20:57 UTC, skarekrow commented on doc/source/advanced-use.rst
>  ---------------
Disclaimer that this is only for legacy implementations, it has not been written for the new version as of yet.

2017-07-05 20:57 UTC, skarekrow commented on doc/source/advanced-use.rst
> +to a text file containing one package name per line. Note an Internet
to a JSON file.

2017-07-05 20:57 UTC, skarekrow commented on doc/source/advanced-use.rst
> +Create a :file:`pkgs.txt` file and add package names to it.
This section needs the pkglist I gave you before, it's not a plain text file.

2017-07-05 20:57 UTC, skarekrow commented on doc/source/advanced-use.rst
> +Now, create a jail and supply :file:`pkgs.txt`:
`.json`

2017-07-05 20:57 UTC, skarekrow commented on doc/source/advanced-use.rst
> +:samp:`# iocage create pkglist=/path-to/pkgs.txt tag=myjail`
`iocage create `--pkglist /path/to/pkg.json --name NAME`

2017-07-07 22:39 UTC, skarekrow requested changes

2017-07-07 22:39 UTC, skarekrow commented on doc/source/advanced-use.rst
> +:command:`iocage clone [UUID|NAME] --name [testupdate]`
We should note that `--name` is optional in this case. If they don't supply it, they will just get a UUID named jail.

2017-07-07 22:39 UTC, skarekrow commented on doc/source/advanced-use.rst
> +:command:`iocage snaplist [UUID|TAG]`
s/TAG/NAME/

2017-07-07 22:39 UTC, skarekrow commented on doc/source/advanced-use.rst
> +:command:`iocage snapshot [UUID|TAG]`
s/TAG/NAME/

2017-07-07 22:39 UTC, skarekrow commented on doc/source/advanced-use.rst
> +Reset Jail Properties
`reset` does not exist anymore. This whole entry can be dropped.

2017-07-07 22:39 UTC, skarekrow commented on doc/source/advanced-use.rst
> +:command:`iocage create -r [RELEASE] -p [path-to/pkgs.json] -n [NAME]`
Should note that `--name` is not required, a UUID jail will be created otherwise.

2017-07-07 22:39 UTC, skarekrow commented on doc/source/advanced-use.rst
I'm not sure if sphinx will automatically put the `{}` and such to make this valid JSON, but if it doesn't we need to make sure the example is proper JSON.

EX:
```
{
    "pkgs": [
    "nginx",
    "tmux"
    ]
}
```

2017-07-11 04:48 UTC, skarekrow requested changes

2017-07-11 04:48 UTC, skarekrow commented on doc/source/advanced-use.rst
> +   new UUID to the clone regardless of **--name** usage.
No, we don't assign a UUID if they use `--name`, if they don't we do.

Example:
`iocage create -n foo -r 11.0-RELEASE` will create a jail named `foo`.
`iocage create -r 11.0-RELEASE` will create a jail named `fd401c05-7777-44e7-9d83-289839f26351` for example.

2017-07-11 04:48 UTC, skarekrow commented on doc/source/advanced-use.rst
> +   jail regardless of its use.
Same note as above :)

2017-07-11 04:48 UTC, skarekrow commented
Close! SO close timmm!

2017-07-11 13:05 UTC, Mrt134 commented
Hopefully, this time'll get it. I got confused with the previous functionality of tags. :)

2017-07-11 21:40 UTC, merged