Fix sorting issues
iocage/iocage pull request #582
Opened 2018-07-07 05:28 UTC by jsegaert

Make sure to follow and check these boxes before submitting a PR! Thank you.

- [x] Explain the feature

This PR addresses various "weird sorting issues" that occur when using the "-s column" option with iocage list, iocage df and/or iocage snaplist.  Refer to issue #482 

- [x] Read [CONTRIBUTING.md](https://github.com/iocage/iocage/blob/master/CONTRIBUTING.md)

2018-07-07 09:00 UTC, skarekrow requested changes
Just a very quick reveiw, this is a nice diff, it will require more testing from me before I merge

As always, thanks :)

2018-07-07 09:00 UTC, skarekrow commented on iocage/lib/ioc_common.py
> +    # jails will be sorted by name within within state
To many within :P

2018-07-07 16:55 UTC, jsegaert commented
Thank you for the heads-up.  Yes, there are quite a few changes.  Happy testing. :-)

2018-07-10 20:50 UTC, skarekrow approved these changes

2018-07-10 20:50 UTC, merged

2018-07-10 20:51 UTC, skarekrow commented
Thanks <3