Fixed iocage list multiple IP4 addresses
iocage/iocage pull request #621
Opened 2018-09-25 04:46 UTC by thedix

This pull request resolves iocage list problem when multiple IP4 addresses specified for jail.
For example, setting ip4_addr="lo1|192.168.1.1,lo1|192.168.2.2" leads to showing "192.168.1.1,lo1" instead of correct "192.168.1.1,192.168.2.2".

2018-09-25 19:27 UTC, skarekrow requested changes

2018-09-25 19:27 UTC, skarekrow commented on iocage_lib/ioc_list.py
> +                short_ip4 = ",".join([item.split("|")[1].split("/")[0] for item in full_ip4.split(",")])
Longer then 79 characters, do a line break on the `"/"` split like this:
```
                short_ip4 = ",".join([item.split("|")[1].split(
                    "/")[0] for item in full_ip4.split(",")])
```

2018-09-26 02:30 UTC, thedix commented
Fixed. Is it ok now?

2018-09-26 19:05 UTC, skarekrow approved these changes

2018-09-26 19:05 UTC, merged

2018-09-26 19:05 UTC, skarekrow commented
Thanks!