Large rework to Exec interface
iocage/iocage pull request #642
Opened 2018-10-06 02:00 UTC by skarekrow

iocage side of #37742, still requires plugin work in freenas/freenas.

- Use python dns.resolver
- Drop other types of DNS tests
- Make Exec a generator
- New Exception type CommandFailed for Exec failures
- Use Exec for RELEASE updating along with jail
- Break console out of Exec
- Log update progress now (means colors as well)

Ticket: #37742

2018-10-06 16:02 UTC, gronke commented on iocage_lib/ioc_exec.py
> +                # postgresql rc.d command never closes the pipe
A good one! I had the same experience with graylog and even had to work with pseudo TTYs to make it start correctly.

2018-10-06 16:04 UTC, gronke approved these changes

2018-10-06 16:13 UTC, gronke requested changes
`import dns` fails because the dependency is not installed. You should add `dnspython` to the list of Python dependencies.

2018-10-06 17:23 UTC, igalic commented on iocage_lib/ioc_exec.py
> +                # postgresql rc.d command never closes the pipe
shouldn't these be submitted as bugs somewhere?

2018-10-07 11:27 UTC, gronke commented on iocage_lib/ioc_exec.py
> +                # postgresql rc.d command never closes the pipe
Seems we have worked around the issue on all ends. But yes, I find it quite unfortunate to rely on a TTY when starting services. We should bring this up and can decide to write a script that tests for similar issues with other services.

2018-10-08 18:56 UTC, skarekrow commented
Wrong target repo

2018-10-08 18:56 UTC, closed without merging