if 'vnet_default_interface' is set to 'none' no host interface will be added to the bridge
iocage/iocage pull request #655
Opened 2018-10-12 13:39 UTC by ole-db

if 'vnet_default_interface' is set to 'none' no host interface will be added to the bridge. 
Auto-detected interface is added to bridge if 'vnet_default_interface' is set to 'auto'

please see https://github.com/iocage/iocage/issues/521

2018-10-12 15:10 UTC, gronke submitted a review, later dismissed
This changes mitigate the issue described in #521.

I still do not get why iocage should create bridges at all.

2018-10-12 19:33 UTC, skarekrow requested changes
In this context `auto` == `none`. So we don't need most of the PR here, However we should not be adding any interface to a bridge if the property is set to `none`, as I noted in the PR.

2018-10-12 19:33 UTC, skarekrow commented on iocage_lib/ioc_start.py
> +                if default_if == 'none':
Let's change this to `if default_if != 'none':` and drop the empty bridge creation, keeping only the else block under this.

2018-10-15 08:18 UTC, skarekrow approved these changes

2018-10-15 08:18 UTC, merged

2018-10-15 08:19 UTC, skarekrow commented
Thanks @ole-db!