Made changes to iocage docs. Came from ticket48768.
iocage/iocage pull request #663
Opened 2018-10-19 17:26 UTC by a-stjohn

Make sure to follow and check these boxes before submitting a PR! Thank you.

- [ x] Explain the feature
Updates to the docs in regard to ticket 48768
- [ x] Read [CONTRIBUTING.md](https://github.com/iocage/iocage/blob/master/CONTRIBUTING.md)

2018-10-20 03:51 UTC, skarekrow requested changes

2018-10-20 03:51 UTC, skarekrow commented on iocage.8
> +Only takes effect when VNET is set and bridge interfaces are not active.
Drop the bridges are active statement here

2018-10-20 03:51 UTC, skarekrow commented on iocage.8
> +Defualt network interface used for the VNET bridge interface in the jail.
Default

2018-10-20 03:51 UTC, skarekrow commented on iocage.8
> +.It Pf vnet_defualt_interface= Op none | Ar INTERFACE
Default

2018-10-20 03:51 UTC, skarekrow commented on iocage.8
> +Defualt: none
Default

2018-10-20 03:51 UTC, skarekrow commented on iocage.8
> +automated testing of PF.
Let’s drop the whole pf statement as it isn’t relevant anymore.

2018-10-20 03:51 UTC, skarekrow commented on iocage.8
>  IPFW is fully supported inside a VNET jail.
Lets say IPFW/pf here

2018-10-20 03:51 UTC, skarekrow commented on iocage.8
> +Use -- in front of specified options to prevent iocage from parsing them.
s/options/command/

2018-10-22 16:20 UTC, a-stjohn commented on iocage.8
>  IPFW is fully supported inside a VNET jail.
Warren does not like slashes. So is this "and" or an "or"? (that, being the reason he doesn't like them)

2018-10-22 20:36 UTC, skarekrow commented on iocage.8
>  IPFW is fully supported inside a VNET jail.
Then say `IPFW and pf` :)

2018-10-22 20:45 UTC, skarekrow commented on iocage.8
> +Use -- in front of specified options to prevent iocage from parsing them.
Why did you mark this resolved? This isn't just options that need it, it's the whole command they specify.
`iocage exec JAIL -- COMMAND` not just options.

2018-10-22 20:47 UTC, skarekrow requested changes
You marked all these as resolved when none of them have been, was that by mistake? Regardless, one more review note.

2018-10-22 20:47 UTC, skarekrow commented on iocage.8
> +Unhides tun devices for the jail with a individual devfsruleset.
`an`

2018-10-23 21:05 UTC, skarekrow requested changes

2018-10-23 21:05 UTC, skarekrow commented on iocage.8
> +The PF firewall is supported inside VNET jails.
Drop this line still :) it's said in the very next line again.

2018-10-25 15:57 UTC, skarekrow approved these changes

2018-10-25 15:58 UTC, merged