No longer start network services explicitly
iocage/iocage pull request #734
Opened 2018-12-18 22:37 UTC by skarekrow

- Use explicit fstab for sysrc during creation
- New syntax for ip4_addr
EXAMPLE : ip4_addr='vnet0|DHCP' 
This replaces dhcp=on, as that previous property would start DHCP on all interfaces, which isn't always desired.
- Simplify setting rc.conf in start to use sysrc for DHCP or rtsold.
- New property 'rtsold', this will enable the service in the jail. This requires having accept_rtadv in the ip6_addr, this new property allows one to rely on just rtsol instead of always starting rtsold.

Closes #711
FreeNAS Ticket: #62547

2018-12-18 22:38 UTC, skarekrow commented
@pmhausen Hey can you test this PR to see if this satisfies your rtsold requirements? Thanks!

2018-12-19 12:18 UTC, william-gr commented on iocage_lib/ioc_create.py
> +                key == 'ip4_addr' and 'DHCP' in value
Requiring DHCP uppercase seems odd. Is there anything which forces DHCP to be set as uppercase?

Perhaps

'dhcp' in value.lower() would make sense?

2018-12-19 12:18 UTC, william-gr commented on iocage_lib/ioc_start.py
> +                    'message': 'Must set atleast one ip6_addr to accept_rtadv!'
atleast

2018-12-19 12:18 UTC, william-gr commented on iocage_lib/ioc_start.py
> +                        ":")[0]
You are not making sense to my OCD. You're switching a bunch of double quotes to single quotes in a lot of PRs. And in this new entire code block you're using double quotes? :P

2018-12-19 12:19 UTC, sonicaj requested changes
There are a few more usages as well where we might break a few other things, referencing them after this comment

2018-12-19 12:19 UTC, sonicaj commented on iocage_lib/ioc_start.py
>              dhcp = 'off'
This will fail unit tests as `wants_dhcp` would not exist

2018-12-19 12:28 UTC, sonicaj commented
How should we handle listing in this case ?
https://github.com/iocage/iocage/blob/548a78681e2c7ac149735e243bb23519bed961e2/iocage_lib/ioc_list.py#L129

2018-12-19 12:29 UTC, sonicaj commented
Not sure if this is breaking or not
https://github.com/iocage/iocage/blob/548a78681e2c7ac149735e243bb23519bed961e2/iocage_lib/ioc_plugin.py#L526

2018-12-19 12:32 UTC, sonicaj commented
Would this require changing as well ?
https://github.com/iocage/iocage/blob/548a78681e2c7ac149735e243bb23519bed961e2/iocage_lib/ioc_plugin.py#L595

2018-12-19 18:27 UTC, skarekrow commented on iocage_lib/ioc_create.py
> +                key == 'ip4_addr' and 'DHCP' in value
DHCP is to mimic the rc.conf entry, since that makes most sense. Also nice and easy to search for later in the code.

2018-12-19 19:08 UTC, william-gr approved these changes

2018-12-19 19:14 UTC, sonicaj approved these changes

2018-12-19 19:14 UTC, merged

2018-12-22 14:11 UTC, pmhausen commented
> @pmhausen Hey can you test this PR to see if this satisfies your rtsold requirements? Thanks!

Of course - as soon as it hits FreeNAS 11.2 - is that scheduled for U1, already?

Kind regards
Patrick

2018-12-22 18:01 UTC, skarekrow commented
This will be in 11.3, too invasive for U1