Improve exception handling
iocage/iocage pull request #802
Opened 2019-01-13 22:33 UTC by sonicaj

This commit improves how we handle exception handling and also fixes an issue where we could not return values from existing exception handler.

2019-01-14 16:13 UTC, skarekrow requested changes
SInce we are no longer using a return value, it seems to me we could drop this for contextlib's suppress and just return the values the same way, without holding onto code ourselves.

2019-01-14 16:15 UTC, sonicaj commented
I have no objections to that. Cleaning up however can still be beneficial. If you think not for now, I can drop all usages altogether then

2019-01-14 16:52 UTC, skarekrow submitted a review, later dismissed

2019-01-14 21:11 UTC, skarekrow submitted a review, later dismissed

2019-01-15 19:19 UTC, skarekrow approved these changes

2019-01-15 19:44 UTC, merged