Use .replace('.', '_') here as well?
iocage/iocage pull request #907
Opened 2019-04-04 20:20 UTC by kcbark

I believe we should replace . with _ here as well as we do in list_get_jid ioc_list.py?
This unborked my jails (named www_test_com) after upgrading from iocage 1.1 to master.

2019-04-04 20:21 UTC, skarekrow requested changes
Yes we should, let's keep the single quotes though :P

2019-04-04 20:37 UTC, skarekrow submitted a review, later dismissed

2019-04-04 20:37 UTC, skarekrow commented on iocage_lib/ioc_json.py
> +                    "jls", "-j", f'ioc-{conf["host_hostuuid"].replace(".", "_")}',
```suggestion
                    'jls', '-j', f'ioc-{conf["host_hostuuid"].replace(".", "_")}',
```

2019-04-04 20:37 UTC, skarekrow submitted a review, later dismissed

2019-04-04 20:38 UTC, skarekrow commented
Thanks @kcbark!

2019-04-05 17:11 UTC, skarekrow commented
@kcbark The travis test will need to be fixed though before merging :)

2019-04-05 18:57 UTC, kcbark commented
Ah, didn’t see that. I’ll fix :)

2019-04-05 19:52 UTC, skarekrow approved these changes

2019-04-05 19:52 UTC, merged