Proxy support for iocage
iocage/iocage pull request #921
Opened 2019-04-23 11:49 UTC by sonicaj

This commit adds proxy support for iocage making sure that proxy provided by cli or set in the environment if library is being used directly is respected.
Ticket: NAS-101365

2019-04-24 01:19 UTC, skarekrow requested changes
This needs to have the proxy support added to lib/iocage so we can use it reliably from the CLI and FreeNAS.

Currently this only supports CLI usage.

2019-04-24 01:19 UTC, skarekrow commented on iocage_cli/create.py
> +    '--proxy', '-S', default=None,
Why `-S`?

2019-04-24 01:19 UTC, skarekrow commented on iocage_lib/ioc_create.py
> +            **os.environ.copy(), "ASSUME_ALWAYS_YES": "yes"
This will leak the users environment during execution (ssh and such), we should keep this minimal and add just the two proxy variables.

2019-04-24 01:19 UTC, skarekrow commented on iocage_lib/ioc_plugin.py
> +            **os.environ.copy(), 'IOCAGE_PLUGIN_IP': ip.rsplit(',')[0]
Same here

2019-04-24 01:19 UTC, skarekrow commented on iocage_lib/ioc_plugin.py
> +                    stdout=su.PIPE, stderr=su.PIPE, env=os.environ.copy()
Same here

2019-04-24 19:44 UTC, skarekrow submitted a review, later dismissed

2019-04-24 23:54 UTC, skarekrow approved these changes

2019-04-25 20:50 UTC, merged

2020-01-10 07:56 UTC, tq02ksu commented
wonderful feature! but I why this can not be used with freeNAS web-UI? Might be the reason that need freenas web-ui update invocation logic to fit the new parameters?

2020-01-10 09:50 UTC, sonicaj commented
@tq02ksu  it can be used with FreeNAS, but is available in latest 11.3 version

2020-01-19 05:21 UTC, tq02ksu commented
@sonicaj Thanks for you infomation!